= JavaEE - Forum
:imagesdir: img
:nofooter:

*Projektarbeit zur Veranstaltung Client-Server Programmierung*
_von: Kajsa Heuer, Pascal Friedrichsen, Dominik Heckner, Fabian Petersen, Cedrik Hoffmann_

== Projektbeschreibung
Aus dem Projekt erfolgt ein Forum, wo ein User Beiträge erstellen und benatworten kann. Das Forum besitzt verschiedene Kategorien, in welche die Beitrage eingefügt werden. Der User kann einen Beitrag beantworten bzw. auch zu einer Antwort zu einem Beitrag einen Kommentar verfassen. Die Resgistrierung / Login erfolgt über eine Eingabemaske und ist der erste Anhaltspunkt, welche der User beim Aufruf der Seite sieht.

Das Projekt wurde in `IntelliJ` erstellt. 


Im Forum kann man Beiträge erstellen, beantworten und bewerten. Die zu erfassenden Daten sind die Nutzerdaten (Name, E-Mail, Passwort, Score) und die Beitragsdaten (Titel, Kategorie, Inhalt, Fragebewertung, Antworten, Antwortbewertung). Jeder Nutzer kann Beiträge erstellen und auf diese Antworten und sie bewerten. Antworten können auch bewertet werden. Registrierung/Login geschieht über eine Eingabemaske. Das Forum besitzt verschiedene Fragekategorien und eine Suchfunktion für die Fragen.


== Vorbereitung
Im folgenden werden die erforderlichen Schritte erläutert, um das Projekt erfolgreich zu testen. Dazu gehört eine auflistung der benötigten Komponenten, die erstellung der Datenbank, sowie das einspielen der Dummydaten.

Die Datei `database.sql` ist ein Export unserer PostgreSQL Datenbank. Diese Datei enthält alle erforderlichen Tabellen und Einträge um das System zu testen.

=== Systemanforderungen
Um das Projekt zum laufen zu bringen, müssen folgende Komponente auf dem Zielsystem vorhanden sein.

- Application Server: `GlassFish 5.1.0`
- Datenbank: `PostgreSQL 14`

=== Datenbank erstellen
Damit die Dump Datei mit den Dummydaten des Projektes erfolgreich eingespielt werden kann, muss zuerst die Datenbank erstellt werden. Damit die Angaben der `persistence.xml` zur Datenbank passen, ist es sinnvoll, die Datenbank wie folgt anzulegen:

[source, sql]
----
CREATE DATABASE javaee_forum;
\connect javaee_forum;

create user javaee_forum_admin with password 'ultra_mega_secret_secure_password';
grant all on schema public to javaee_forum_admin;
alter schema public owner to javaee_forum_admin;
----

=== Datenbank befüllen
Um die Datenbank zu befüllen, wird das von Postgres mitgelieferte Tool `psql` benötigt. Die Datei kann nun wie folgt eingespielt werden:
[listing]
----
psql javaEE_forum < [PATH_TO_SQL_FILE]
----

== Dokumentationen
- Datenbank https://github.com/choffmann/javaEE-forum/tree/main/Doku/Database[Dokumentation]
- REST Schnittstelle https://github.com/choffmann/javaEE-forum/tree/main/Doku/REST_Api[Dokumentation]
- Frontend https://github.com/choffmann/javaEE-forum/tree/main/Doku/User_Interface#readme[Dokumentation]
