= JavaEE - Forum
:imagesdir: img
:nofooter:

== Projektbeschreibung
Im Forum kann man Beiträge erstellen, beantworten und bewerten. Die zu erfassenden Daten sind die Nutzerdaten (Name, E-Mail, Passwort, Score) und die Beitragsdaten (Titel, Kategorie, Inhalt, Fragebewertung, Antworten, Antwortbewertung). Jeder Nutzer kann Beiträge erstellen und auf diese Antworten und sie bewerten. Antworten können auch bewertet werden. Registrierung/Login geschieht über eine Eingabemaske. Das Forum besitzt verschiedene Fragekategorien und eine Suchfunktion für die Fragen.

=== System
- Application Server: `GlassFish 5.1.0`
- Datenbank: `PostgreSQL`
- HTTP, Application Server, Servlet, JSP, REST, Datenbank, JPA (Dazu Context and Dependency Injection)
- JSON, kein XML

== Postgres *.sql einspielen
Die Datei `database.sql` enthält die benötigten Tabellen für die Anwendung. Der Inhalt der Tabellen ist nicht befüllt.

Um die `Dump-Datei` nun einzuspielen, muss natürlich zuerst eine entsprechende Datenbank erstellt werden, z.B.:
[listing]
----
create database javaEE_forum;;
create Creator javaEE_forum_admin password 'ultra_mega_secret_secure_password' login;
----

Zum eingespielt wird das von Postgres mitgelieferte Tool `pg_restore` benötigt. Die Datei  kann nun wie folgt eingespielt werden:
[listing]
----
pg_restore -h localhost -d javaEE_forum < [PATH_TO_SQL_FILE]
----

== Schritte
1. Datenbank erstellen und JPA Schnittstelle erstellen https://github.com/choffmann/javaEE-forum/tree/database/Doku/Database[siehe Doku]
2. REST Schnittstelle definieren
3. Frontend erstellen