= Datenbank - Doku
:imagesdir: img
:nofooter:

Die Datenbank wird mit `PostgreSQL` realisiert. Innerhalb des Projektes erfolgt der zugriff auf die Datenbank mittels `JPA (Java Persistence API)`

== Tabellen
.Creator
|===
|Name |Typ

|id
|`BIGSERIAL` `PRIMARY KEY`

|Creatorname
|`TEXT`

|email
|`TEXT`

|password
|`TEXT`

|is_admin
|`BOOL`

|score
|`INT`
|===

.Category
|===
|Name |Typ

|id
|`BIGSERIAL` `PRIMARY KEY`

|text
|`TEXT`

|===

.Thread
|===
|Name |Typ

|id
|`BIGSERIAL` `PRIMARY KEY`

|creator
|`Creator` `OneToOne`

|title
|`TEXT`

|created_at
|`DATETIME`

|modified_at
|`DATETIME`

|text
|`TEXT`

|category
|`Category` `OneToMany`
|===

.Thread_Tags
|===
|Name |Typ

|thread
|`Thread` `PRIMARY KEY`

|tag
|`TEXT`
|===

.Answer
|===
|Name |Typ

|id
|`BIGSERIAL` `PRIMARY KEY`

|thread
|`Thread` 

|creator
|`Creator`

|created_at
|`DATETIME`

|modified_at
|`DATETIME`

|text
|`TEXT`
|===

.Comment
|===
|Name |Typ

|id
|`BIGSERIAL` `PRIMARY KEY`

|answer
|`Answer`

|creator
|`Creator`

|created_at
|`DATETIME`

|modified_at
|`DATETIME`

|text
|`TEXT`
|===

.Creator_Answer
|===
|Name |Typ

|Creator
|`Creator` `PRIMARY KEY`

|answer
|`Answer` `PRIMARY KEY`

|validation
|`BOOL`
|===

== Erstellung
.User und Datenbank
[listing]
----
create database javaEE_forum;
create user javaEE_forum_admin password 'ultra_mega_secret_secure_password' login;
grant all on database javaEE_forum to javaEE_forum_admin;
grant all privileges on all tables in schema public to javaEE_forum_admin;
grant usage, select on all sequences in schema public to javaee_forum_admin;
----

.Creator Table
[source, sql]
----
CREATE TABLE Creator (
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT NOT NULL,
    password TEXT NOT NULL,
    is_admin BOOLEAN NOT NULL DEFAULT false,
    score NUMERIC NOT NULL DEFAULT 0
);
----

.Category Table
[source, sql]
----
CREATE TABLE Category (
    id SERIAL PRIMARY KEY,
    text TEXT NOT NULL
);
----

.Thread Table
[source, sql]
----
CREATE TABLE Thread (
    id SERIAL PRIMARY KEY,
    creator INT REFERENCES Creator(id),
    title TEXT NOT NULL,
    created_at DATE NOT NULL DEFAULT CURRENT_DATE,
    modified_at DATE NOT NULL,
    text TEXT NOT NULL,
    category INT REFERENCES Category(id)
);
----

.Tag Table
[source, sql]
----
CREATE TABLE Tag (
    id SERIAL PRIMARY KEY,
    tag TEXT NOT NULL
);
----

.Thread_Tag Table
[source, sql]
----
CREATE TABLE Thread_Tag (
    thread_id INT REFERENCES Thread(id),
    tag_id INT REFERENCES Tag(id),
    CONSTRAINT thread_tag_pkey PRIMARY KEY (thread_id, tag_id)
);
----

.Answer Table
[source, sql]
----
CREATE TABLE Answer (
    id SERIAL PRIMARY KEY,
    thread INT REFERENCES Thread(id),
    creator INT REFERENCES Creator(id),
    created_at DATE NOT NULL DEFAULT CURRENT_DATE,
    modified_at DATE NOT NULL,
    text TEXT NOT NULL
);
----

.Comment Tablex
[source, sql]
----
CREATE TABLE Comment (
    id SERIAL PRIMARY KEY,
    answer INT REFERENCES Answer(id),
    creator INT REFERENCES Creator(id),
    created_at DATE NOT NULL DEFAULT CURRENT_DATE,
    modified_at DATE NOT NULL,
    text TEXT NOT NULL
);
----

.Creator_Answer Table
[source, sql]
----
CREATE TABLE Creator_Answer (
    creator_id INT REFERENCES Creator(id),
    answer_id INT REFERENCES Answer(id),
    validation BOOLEAN NOT NULL,
    CONSTRAINT creator_answer_pkey PRIMARY KEY (creator_id, answer_id)
);
----

.Creator_Comment Table
[source, sql]
----
CREATE TABLE Creator_Comment (
    creator_id INT REFERENCES Creator(id),
    comment_id INT REFERENCES Comment(id),
    CONSTRAINT creator_comment_pkey PRIMARY KEY (creator_id, comment_id)
);
----